### ISSUE TITLE
about "Not Supportable Operating System!"

### ISSUE THREAD

**Issue by huitc** [hash3liZer/WiFiBroot#10]
how can i use wifibroot on windows (10)?
win10 64bit
I have installed Scapy, wheel, Curses...

https://www.jianshu.com/p/953b3a738ee0

```
# python2 wifibroot.py

 _        ___  ___ ___  ___   ___
 \\  _ /\*\___*\__\\__\/   \ /   \\___
  \  \\  \\\   \\__\\ /\  ) \\  ) \\  \
   \__\\__\\\   \\__\\ \\__ / \___/ \__\

          v1.0. Coded by @hash3liZer.

[~] Not Supportable Operating System!
```

**Comment by hash3liZer** [comment]
You can't use WiFiBroot on windows. To use WiFiBroot, you need to enable Monitor mode on your wireless card which isn't supported in windows operating system. That's why it doens't support windows yet.

**Comment by osysltd** [comment]
For Windows search for airwin

**Comment by hash3liZer** [comment]
@osysltd Can you post some link or guide that could help?

**Comment by huitc** [comment]
but I can use it on vbox... why windows can't and vbox can?...😣

**Comment by hash3liZer** [comment]
@huitc Because inside VBOX, the system you are running is considered to be Linux. Wait, i am gonna remove this anyway, just let me do a push.

**Comment by hash3liZer** [comment]
Check now, i've pushed a new commit. You will no longer receive this error.
