### ISSUE TITLE
Exception in thread Verbose Sniffer: ERROR

### ISSUE THREAD

**Issue by 3nboos** [hash3liZer/WiFiBroot#13]
first thanks for making such great powerful tool , this shows how smart you are.
I am so sad that I can't scan my networks though :cry: 

I already tried what you said `-e or -bssid 2WIREWIFIname` 
that Doesn't show any wifi at all keeps hoping on channels only

here is the code I get `RIS        1
Exception in thread Verbose Sniffer:
                                    Traceback (most recent call last):
                                                                        File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                                  self.run()
                                                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                                          self.__target(*self.__args, **self.__kwargs)
                        File "/root/WiFiBroot/screen.py", line 83, in Shifter
                                                                                 self.screen.addstr(1, 0, "\n"+tabulate(tabulator__, headers=__HEADERS)+"\n")
                                                                             TypeError: int,int,str

[`]()
i can't post an image here is a link

https://i.imgur.com/gQ54dTM.png

**Comment by hash3liZer** [comment]
You are right, seems like a bug to me. Anyways, I've got some other bugs in the current version as well. The program is still under testing. For the current situation, you can solve the problem by skipping the `--verbose` option. That is causing the problem. Let met know if that works for you.

**Comment by hash3liZer** [comment]
Hey, it seems like the error is coming from the newest scapy version. Please install the following scapt version: `2.4.0`. That is likely to solve your problem.
