### ISSUE TITLE
Are this is work on termux android?

### ISSUE THREAD

**Issue by Uluum** [hash3liZer/WiFiBroot#20]
Can this is work on termux?

**Comment by hash3liZer** [comment]
Maybe, but it is not tested on termux. To use it on termux, you will need your wireless card in monitor mode with scapy installed.

**Comment by vaibhav-rm** [comment]
It's gives me this error in termux :- 
u0_a233@localhost ~/WiFiBroot (master) [1]> python2 wifibroot.py
Traceback (most recent call last):
  File "wifibroot.py", line 17, in <module>
    from screen import Display
  File "/data/data/com.termux/files/home/WiFiBroot/screen.py", line 2, in <module>
    from scapy.utils import hexdump
ImportError: No module named scapy.utils
u0_a233@localhost ~/WiFiBroot (master) [1]>
