### ISSUE TITLE
total beginner question  

### ISSUE THREAD

**Issue by ahmedbenammar029** [hash3liZer/WiFiBroot#21]
hey great tool, I'm currently learning how to code and I just want better internet so I have no time to learn about networks right now, so as far as I know, I need to install Linux OS and a network adapter, right ??

**Comment by hash3liZer** [comment]
Yes, would be better if you start with Kali Linux or Parrot and atleast buy TP-Link WN722N v1. Otherwise, whatever adapter you buy, make sure it supports packet injection.
