### ISSUE TITLE
how to fix this ??

### ISSUE THREAD

**Issue by raeediq97** [hash3liZer/WiFiBroot#24]
root@a-Inspiron-M5040:/home/a/Downloads/WiFiBroot-master# python3 wifibroot.py -m 2 -i wlan0mon --verbose -d dicts/list.txt -w output.txt

 _        ___  ___ ___  ___   ___
 \\  _ /\*\___*\__\\__\/   \ /   \\___
  \  \\  \\\   \\__\\ /\  ) \\  ) \\  \
   \__\\__\\\   \\__\\ \\__ / \___/ \__\

          v1.0. Coded by @hash3liZer.

[*] Path: {dicts/list.txt} Lines {41}
Traceback (most recent call last):
  File "wifibroot.py", line 607, in <module>
    main()
  File "wifibroot.py", line 576, in main
    iface = _channeler(options); _silf = _silfer(iface, options)
  File "wifibroot.py", line 464, in _channeler
    iface = interface(options.interface)
  File "wifibroot.py", line 51, in __init__
    self.check_man = self.check_man()
  File "wifibroot.py", line 56, in check_man
    if self.is_man(self.iface):
  File "wifibroot.py", line 103, in is_man
    card = re.findall('Mode:[A-Za-z]+', data)[0]
  File "/usr/lib/python3.6/re.py", line 222, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by a7853z** [comment]
same error

**Comment by frostKn** [comment]
just run it with python2 

pip2 install pbkdf2
python2 wifibroot.py -i [interface] -d /path/to/dictionary -m [mode]

**Comment by HappyCampero76** [comment]
hi guys just downloadd wifibroot.py,as soon as i launched the tool gave me the following error:
~/WiFiBroot# python wifibroot.py --m 4 --h
  File "wifibroot.py", line 197
    print "\n"+tabulate(tabulator__, headers=__HEADERS)+"\n"
             ^
SyntaxError: invalid syntax
what should i do to fix it?
many thanks in advance!!

**Comment by hash3liZer** [comment]
@HappyCampero76 Hi, i think the version you are using is python 3. I've now explicitly mentioned it in the manual. Use python 2.

**Comment by hash3liZer** [comment]
If you have pbkdf2 error, install it through pip

**Comment by HappyCampero76** [comment]
> @HappyCampero76 Hi, i think the version you are using is python 3. I've now explicitly mentioned it in the manual. Use python 2.

well i installed what you said but i still get the same error...
root@AMD-MadDog76:~/WiFiBroot# python wifibroot.py
  File "wifibroot.py", line 197
    print "\n"+tabulate(tabulator__, headers=__HEADERS)+"\n"
             ^
SyntaxError: invalid syntax

**Comment by HappyCampero76** [comment]
> > @HappyCampero76 Hi, i think the version you are using is python 3. I've now explicitly mentioned it in the manual. Use python 2.
> 
> well i installed what you said but i still get the same error...
> root@AMD-MadDog76:~/WiFiBroot# python wifibroot.py
> File "wifibroot.py", line 197
> print "\n"+tabulate(tabulator__, headers=__HEADERS)+"\n"
> ^
> SyntaxError: invalid syntax

pip install scapy==2.4.0
Collecting scapy==2.4.0
  Downloading https://files.pythonhosted.org/packages/68/01/b9943984447e7ea6f8948e90c1729b78161c2bb3eef908430638ec3f7296/scapy-2.4.0.tar.gz (3.1MB)
    100% |████████████████████████████████| 3.1MB 180kB/s 
Building wheels for collected packages: scapy
  Running setup.py bdist_wheel for scapy ... done
  Stored in directory: /root/.cache/pip/wheels/cf/03/88/296bf69fee1f9ec7a87e122da52253b65f3067f6ea8719b473
Successfully built scapy
Installing collected packages: scapy
  Found existing installation: scapy 2.4.2
    Uninstalling scapy-2.4.2:
      Successfully uninstalled scapy-2.4.2
Successfully installed scapy-2.4.0
You are using pip version 9.0.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by hash3liZer** [comment]
Show me the output of : python --version

**Comment by HappyCampero76** [comment]
> Show me the output of : python --version

# python --version
Python 3.6.6 :: Anaconda, Inc.

**Comment by hash3liZer** [comment]
As you can see, its still python version 3. You need to specifically install python version 2. Check for offical documentation on how to do so.

**Comment by HappyCampero76** [comment]
oh ok i will do so ty
