### ISSUE TITLE
Client is showing 0

### ISSUE THREAD

**Issue by jepunband** [hash3liZer/WiFiBroot#29]
hi , scanning produces 0 clients. Tested with my own network with few devices connected but scanning shows 0 clients. If
AP Clients [0] Scan Further?[Y/n] Y , this option is taking too long to scan.

**Comment by hash3liZer** [comment]
You are probably running a 4-way handshake attack. To perform it, you need at least a client connected to the target AP. Whilst in your case, it seems as if there are no clients connected.

**Comment by hash3liZer** [comment]
Closing as of no response!
