### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by soupnatzi** [hash3liZer/WiFiBroot#3]
python wifibroot.py -i wlan1
Traceback (most recent call last):
  File "wifibroot.py", line 18, in <module>
    from wireless import Shifter
  File "/root/Desktop/newtools/WiFiBroot/wireless/__init__.py", line 3, in <module>
    from wireless.cracker import PSK
  File "/root/Desktop/newtools/WiFiBroot/wireless/cracker.py", line 6, in <module>
    from pbkdf2 import PBKDF2
ImportError: No module named pbkdf2

**Comment by soupnatzi** [comment]
am an idiot never mind this issue is not even a issue

**Comment by hash3liZer** [comment]
Which Operating System are you using?

**Comment by hash3liZer** [comment]
If you are on Linux and still receiving this error, you are missing a library `pbkdf2`. Tough it should be already on your system, you can manually install it: 
```
$ pip install pbkdf2
```
Or if don't work: 
```
$ apt-get install python-pbkdf2
```

**Comment by soupnatzi** [comment]
yea i know am doing ten things at once and just didnt realise what i needed to get.all good

**Comment by hash3liZer** [comment]
Your problem solved?

**Comment by hash3liZer** [comment]
Closing this, since no response.

**Comment by zuhaircmr** [comment]
> If you are on Linux and still receiving this error, you are missing a library `pbkdf2`. Tough it should be already on your system, you can manually install it:
> 
> ```
> $ pip install pbkdf2
> ```
> 
> Or if don't work:
> 
> ```
> $ apt-get install python-pbkdf2
> ```

This worked for me . thanks @hash3liZer
