### ISSUE TITLE
EAPOL AttributeError 

### ISSUE THREAD

**Issue by Hack4Live** [hash3liZer/WiFiBroot#4]
I get this after a few Association Requests
[*] Waiting For EAPOL to initate...
Exception in thread Association Depender:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/WiFiBroot/wireless/pmkid.py", line 143, in asso_sniffer
    sniff(iface=iface, prn=self.get_asso_resp)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 620, in sniff
    r = prn(p)
  File "/root/WiFiBroot/wireless/pmkid.py", line 163, in get_asso_resp
    nonce = binascii.hexlify(pkt.getlayer(Raw).load)[26:90]
AttributeError: 'NoneType' object has no attribute 'load'

[^] 1 Frames 843A4B66DB70 > 5E4979CE1679 [Association Request]
Then it goes on  and comes again

**Comment by hash3liZer** [comment]
Looks like some malformed packet. Can you send me details of the target network?

**Comment by Hack4Live** [comment]
It doesnt work on any network i Tried

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by hash3liZer** [comment]
Which scapy version are you using?

**Comment by Hack4Live** [comment]
2.3.3

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by hash3liZer** [comment]
I've installed your scapy version and got some other errors as well. Looks like something to do with previous versions. Why don't you install the latest 2.4.x version. 
Just do: 
```
pip uninstall scapy && pip install scapy
```
Make sure you are running the latest version. 
For now, i am gonna try to make a patch for the previous versions. I'll update your ticket. 
Hope it would work.

**Comment by Hack4Live** [comment]
Okay seems to be working now thanks!:)

**Comment by hash3liZer** [comment]
Closing the issue...
