### ISSUE TITLE
Issue when running initial AP scan

### ISSUE THREAD

**Issue by chromedome94** [hash3liZer/WiFiBroot#5]
I have done everything I can think of in order to fix this issues and could really use some assistance. When I run: 
python wifibroot.py -i wlan0 --dictionary wordlist.txt -m 1

(note: I have tried to run the program every single way recommended by other guides as well) 

I get the following results:  

NO  ESSID         PWR  ENC    CIPHER    AUTH      CH  BSSID
----  ----------  -----  -----  --------  ------  ----  -----------------
   1  ***********    -48  WPA2   CCMP      PSK        1  **:**:**:**:**:**
Exception in thread Verbose Sniffer:
                                    Traceback (most recent call last):
                                                                        File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
      self.run()
                  File "/usr/lib/python2.7/threading.py", line 754, in run
                                                                              self.__target(*self.__args, **self.__kwargs)
                                                                                                                            File "/root/WiFiBroot/screen.py", line 83, in Shifter
                                         self.screen.addstr(1, 0, "\n"+tabulate(tabulator__, headers=__HEADERS)+"\n")
                                                                                                                     TypeError: int,int,str

                                                                                                                                           [?] Enter Your Target Number [q]uit/[n]: 

I should also mention that the terminal is frozen at this point and I have to completely close it out. Sometimes I won't get any APs before the error occurs and other times I will get 2 with the error immediately following. 

Please help!

Thnks!

**Comment by hash3liZer** [comment]
Thanks, for opening the issue. This surely is a bug. Can you provide me with your Operating System, version, and terminal version.

**Comment by chromedome94** [comment]
I am running Kali Linux 2018.2 which is the kali-rolling release. With the 4.17.0-kali3-amd64 linux kernel. My terminal is a bash terminal...if that would make a difference.

**Comment by hash3liZer** [comment]
Hey, I've just pushed two commits under the released version 1.3. I've also added a new offline cracking mode. Hope, this would solve you problem. Can you verify it now? Also make sure, that you have the latest version of scapy.

**Comment by hash3liZer** [comment]
I am closing the issue since no response from user has yet received. However, this error occurs because of illegeal characters in the network ESSID. If the problem still persists, supply `--essid, -e` option for skipping unwanted networks.
