### ISSUE TITLE
self screen error

### ISSUE THREAD

**Issue by hakimarx** [hash3liZer/WiFiBroot#7]
when i start wifibroot, appear like this

  10  SSID      -85  WPA2/WPA  TKIP      PSK        3  34:0A  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  11      self.run()A     -85  WPA2      TKIP      PSK        1  5X:XX:XX:XX:00:XX  Huawei       0
                      File "/usr/lib/python2.7/threading.py", line 754, in run
                                                                                  self.__target(*self.__args, **self.__kwargs)
                                                                                                                                File "/home/h/WiFiBroot/screen.py", line 83, in Shifter
                                                   self.screen.addstr(1, 0, "\n"+tabulate(tabulator__, headers=__HEADERS)+"\n")
                                                                                                                               TypeError: int,int,str

**Comment by hash3liZer** [comment]
The error occurs because of unexpected data in packets sniffed through the air. I am currently working on it. Until then, try to specify your target essid directly with argugment `--essid`: 

```
$ python wifibroot.py --essid <TARGET> ...
```

**Comment by simon1tan** [comment]
I still get this error. is this fixed? Why closed?
