### ISSUE TITLE
Dont work under scapy-2.4.2

### ISSUE THREAD

**Issue by wifislax-ng** [hash3liZer/WiFiBroot#8]
Traceback (most recent call last):
  File "wifibroot.py", line 19, in <module>
    from wireless import Shifter
  File "/usr/share/wifibroot/wireless/__init__.py", line 2, in <module>
    from wireless.sniper import Sniper
  File "/usr/share/wifibroot/wireless/sniper.py", line 7, in <module>
    from scapy.layers.dot11 import Raw
ImportError: cannot import name Raw

**Comment by hash3liZer** [comment]
Sorry, for the late fix. We are working on it. It will be shortly fixed. Scapy developers have replaced the Raw class from `scapy.layers.dot11` to `scapy.packet` package.

**Comment by hash3liZer** [comment]
Hey, @wifislax-ng . It seems as if scapy has been changed a lot since the last version. Now, i am getting multiple exceptions. They have misplaced a lot of things, even the field inside the `classes`. Up until i get it to work to on the newer version, i am pushing a temporary fix for scapy 2.4.0. You can install scapy `2.4.0` until i release the new version: 

```
$ pip uninstall scapy
$ pip install scapy==2.4.0
```

**Comment by ajd394** [comment]
https://github.com/secdev/scapy/blob/master/scapy/layers/dot11.py#L619
https://github.com/secdev/scapy/blob/master/test/regression.uts#L10567

Looks like you can now pull the PMKIDs directly out without using Raw.

**Comment by hash3liZer** [comment]
Yeah, actually they have replaced some of the internal fields, PMKID is not an issue for me yet, i am still able to extract it tough. I am having some problem extracting WPA/WPA encyrption algorithms. I am rebuilding the whole thing. It would take some time.  BTW `2.4.0` is working fine.

**Comment by hash3liZer** [comment]
WiFiBroot is built on scapy version `2.4.0`. So, anyone seeing the problems above can install the suitable version.

**Comment by gpotter2** [comment]
Hi, a Scapy maintainer here. Feel free to ask any question regarding the newest versions / compatibility (2.4.3 was released right before BlackHat)

**Comment by bryce-lynch** [comment]
I have the same issue with scapy 2.4.3. IMO should just avoid using Raw as suggested by ajd394, instead of sticking to an insecure version (2.4.0) of scapy.

**Comment by c14it0n** [comment]
Hello, with scapy version 2.4.2 gives the following error when starting the tool:


Traceback (most recent call last):
  File "wifibroot.py", line 17, in <module>
    from screen import Display
  File "/home/kali/WiFiBroot/screen.py", line 2, in <module>
    from scapy.utils import hexdump
ImportError: No module named scapy.utils
